### PR TITLE
remove msg and srv which use data that cannot be accessed through Blueprint

### PR DESCRIPTION
**Pull request by tetorea**
Only int32, int64 and float32 can be accessed with Blueprint
Compilation errors occur when trying to set UPROPERTY to these other types : int8, int16, float64, double, uint8, uint16, uint32, uint64

### CODE REVIEW

**Review by yuokamoto — APPROVED** [review]

**Comment by Tadinu** [comment]
I remember hearing someone of us talking about this a while ago, so just to confirm:
* Since rclUE would be meant to support either Blueprint or cpp clients or both, should we keep those for cpp client users?
* It's a bit strange that in the [doc](https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/GameplayArchitecture/Properties/) they mention all types.
* [Here](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Plugins/AI/UE4ML/Source/UE4ML/Public/Sensors/4MLSensor_Camera.h:44), `uint32` is actually used with `UPROPERTY`
Some refs:
https://answers.unrealengine.com/questions/98206/missing-support-for-uint32-int64-uint64.html

**Comment by Tadinu** [comment]
I remember hearing someone of us talking about this a while ago, so just to confirm:
* Since rclUE would be meant to support either Blueprint or cpp clients or both, should we keep those for cpp client users?
* It's a bit strange that in the [doc](https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/GameplayArchitecture/Properties/) they mention all types.
* [Here](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Plugins/AI/UE4ML/Source/UE4ML/Public/Sensors/4MLSensor_Camera.h:44), `uint32` is actually used with `UPROPERTY`
Some ref with answer from Epic staff (probably they have already updated to some extent by now):
https://answers.unrealengine.com/questions/98206/missing-support-for-uint32-int64-uint64.html

**Comment by Tadinu** [comment]
I remember hearing someone of us talking about this a while ago, so just to confirm:
* Since rclUE would be meant to support either Blueprint or cpp clients or both, should we keep those for cpp client users?
* It's a bit strange that in the [doc](https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/GameplayArchitecture/Properties/) they mention all types.
* [Here](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Plugins/Developer/RenderDocPlugin/Source/RenderDocPlugin/Public/RenderDocPluginSettings.h#L18), `uint32` is actually used with `UPROPERTY`
Some ref with answer from Epic staff (probably they have already updated to some extent by now):
https://answers.unrealengine.com/questions/98206/missing-support-for-uint32-int64-uint64.html

**Comment by tetorea** [comment]
> I remember hearing someone of us talking about this a while ago, so just to confirm:
> 
>     * Since rclUE would be meant to support either Blueprint or cpp clients or both, should we keep those for cpp client users?
> 
>     * It's a bit strange that in the [doc](https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/GameplayArchitecture/Properties/) they mention all types.
> 
>     * [Here](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Plugins/Developer/RenderDocPlugin/Source/RenderDocPlugin/Public/RenderDocPluginSettings.h#L18), `uint32` is actually used with `UPROPERTY`
>       Some ref with answer from Epic staff (probably they have already updated to some extent by now):
>       https://answers.unrealengine.com/questions/98206/missing-support-for-uint32-int64-uint64.html

Yes, I think it was Conti who talked about this before.
- I guess we could keep the cpp only class and not expose them to Blueprint to avoid confusion
- they don't mention explicitly that all types are supported but their presentation is ambiguous. I actually tried to compile all the types with uproperty and I removed the ones which had compilation errors
- in the forum message, it's the user who implemented its own version, if I understand correctly, but he doesn't say how. From this message, only support for int64 has been added apparently. My compiler accepts only int32, int64 and float32

**Pull request merged**
